---
# This Ansible playbook deploys a complete mirror setup including statistics
- hosts: all
  roles:
    - common
    - goaccess
    - archlinux
    - centos
    - debian
    - dotdeb
    - epel
    - ubuntu
    - debian-security
